### ISSUE TITLE
Window pops up breifly

### ISSUE THREAD

**Issue by ptarjan** [hhvm/vim-hack#10]
Sometimes when I save, the window at the bottom pops up very quickly, then immediately goes away and leaves me in a state of off-by-one in the parts that haven't redrawn yet. Doing a `:redraw!` fixes it or scrolling the code out of view and then back works too.

**Comment by fredemmott** [comment]
resolved by #40; this functionality is now provided via the LSP - see https://github.com/hhvm/vim-hack/blob/master/README.md for instructions.
