### ISSUE TITLE
Remote typechecking

### ISSUE THREAD

**Issue by girvo** [hhvm/vim-hack#16]
Hey there, 

A key feature (while HHVM is broken on OS X) that would make Hack so much easier to work with is to take advantage of the client-server architecture the typechecker has.

Currently, I run HHVM in a Docker container (in a Boot2Docker VM) on an OS X host, and this works well enough (I can run the type checker through `ssh` and get the output in the console). It would be amazing if `vim-hack` could do the same: give it an SSH command that it will execute it's calls to `hh_client`/`hh_server` through. 

Is this possible through Vim? I'm honestly unsure.

**Comment by jwatzman** [comment]
> Is this possible through Vim? I'm honestly unsure.

So, I don't know the answer to the actual issue you're filing here -- @mxw probably does and can comment when he sees it. However, there are a couple of other options:

- Write your code in a shared folder between the host and VM, so you can run `hh_client` directly on OS X with the existing support. (The issues with `hh_server` and shared folders only comes up when you are editing on a different machine than where `hh_server` is running.) Not necessarily great, but not super difficult to set up, and it should work right now :)
- Over the next few months, I want to add a small `hh_client` into HHVM itself, so you can, for example, just poke it over an admin port and get your type errors that way, so `hh_server` can just run in the VM but tools like `vim` can have an easy way to get info out. This isn't built yet, and won't be for a while, but if doing the `ssh` thing in `vim` is hard, it might be worth just waiting for this.

**Comment by fredemmott** [comment]
I've had success pointing nuclide at https://github.com/fredemmott/nuclide-customization/blob/master/docker-hh_client instead of a real hh_client, similar would probably work for vim-hack

**Comment by fredemmott** [comment]
resolved by #40; this functionality is now provided via the LSP - see https://github.com/hhvm/vim-hack/blob/master/README.md for instructions.

If you're using LanguageClient-neovim, you can set the executable to something like `ssh foo hh_client`
