### ISSUE TITLE
Prevent syntax coloring if not hack file

### ISSUE THREAD

**Issue by Taluu** [hhvm/vim-hack#19]
As the coloring file is `php.vim`, if hack is not used but plain old php, if using StanAngeloff's coloring (https://github.com/StanAngeloff/php.vim), it seems to erase that file.

I think this should not happen ; how about setting a brand new type (hence a new file) instead ?

**Comment by jgimeno** [comment]
For me it would be good to define a hh file type. Because I only need hack autocomplete when it's a real hack file, if not I want my phpcd autocompletion which now i can't.

**Comment by jgimeno** [comment]
https://github.com/hhvm/vim-hack/pull/26

Take a look Taluu.

**Comment by jwatzman** [comment]
Hack code can live in `.php` files, see my comment on #26.
