### ISSUE TITLE
I don't seem to get the omnifunc to work

### ISSUE THREAD

**Issue by spidfire** [hhvm/vim-hack#20]
I contstantly get: `-- Omni completion (^O^N^P) Pattern not found`
after I do Ctrl+x Ctrl+o

Part from my .vimrc

```
Bundle 'hhvm/vim-hack'
let g:hack#autoclose = 1
let g:hack#enable=1

filetype plugin on
set omnifunc=hackcomplete#Complete

```

Do I overlook something?

**Comment by fredemmott** [comment]
resolved by #40; this functionality is now provided via the LSP - see https://github.com/hhvm/vim-hack/blob/master/README.md for instructions.
