### ISSUE TITLE
.hack Files No Supported Syntax

### ISSUE THREAD

**Issue by mike2151** [hhvm/vim-hack#48]
Hello,

I noticed here: [https://github.com/hhvm/vim-hack/blob/master/ftdetect/hack.vim#L14](https://github.com/hhvm/vim-hack/blob/master/ftdetect/hack.vim#L14) that you set the syntax to be hack. 

However, looking at [vim syntaxes](https://github.com/vim/vim/tree/master/runtime/syntax), I notice there is no hack.vim file.

Why not just set the syntax to be PHP?

**Comment by Wilfred** [comment]
There is a hack.vim file in this repo, but I will defer to @fredemmott to clarify vim best practices.

**Comment by fredemmott** [comment]
Yep, this repo includes hack syntax.

Pure PHP syntax can not handle many parts of hack syntax, or any .hack files (which do not have a <? header)
